name: macstadium-build-aar

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  ANDROID_HOME: /Users/administrator/Library/Android/sdk

jobs:
  build:
    name: Build SDK AAR
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build AAR
        run: ./gradlew clean assembleRelease -Pcloudx.endpoint.config=https://example.com/config.json

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudx-sdk-aar
          path: build/outputs/aar/*.aar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: build/outputs/aar/*.aar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

