name: macstadium-build-sdk-android

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  ANDROID_HOME: /Users/administrator/Library/Android/sdk

jobs:
  build:
    name: build-sdk-android
    runs-on: self-hosted
    outputs:
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url  }}
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew :sdk:test
      - name: 📊 Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ github.run_number }}
          path: |
            sdk/build/reports/tests/
            sdk/build/test-results/
      - name: 📋 Generate Test Summary
        if: always()
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          if [ -f sdk/build/test-results/test/TEST-*.xml ]; then
            TOTAL=$(grep -o 'tests="[0-9]*"' sdk/build/test-results/test/TEST-*.xml | head -1 | grep -o '[0-9]*')
            FAILURES=$(grep -o 'failures="[0-9]*"' sdk/build/test-results/test/TEST-*.xml | head -1 | grep -o '[0-9]*')
            ERRORS=$(grep -o 'errors="[0-9]*"' sdk/build/test-results/test/TEST-*.xml | head -1 | grep -o '[0-9]*')
            SKIPPED=$(grep -o 'skipped="[0-9]*"' sdk/build/test-results/test/TEST-*.xml | head -1 | grep -o '[0-9]*')
            PASSED=$((TOTAL - FAILURES - ERRORS - SKIPPED))

            if [ $((FAILURES + ERRORS)) -eq 0 ]; then
              echo "✅ All tests passed!" >> $GITHUB_STEP_SUMMARY
            else
              echo "❌ Some tests failed!" >> $GITHUB_STEP_SUMMARY
            fi

            echo "" >> $GITHUB_STEP_SUMMARY
            echo "- **Total:** $TOTAL" >> $GITHUB_STEP_SUMMARY
            echo "- **Passed:** ✅ $PASSED" >> $GITHUB_STEP_SUMMARY
            echo "- **Failed:** ❌ $((FAILURES + ERRORS))" >> $GITHUB_STEP_SUMMARY
            echo "- **Skipped:** ⏭️ $SKIPPED" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ No test results found" >> $GITHUB_STEP_SUMMARY
          fi
      - name: Extract version from libs.versions.toml
        id: extract-version
        run: |
          VERSION=$(grep '^sdkVersionName = ' gradle/libs.versions.toml | sed 's/sdkVersionName = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
          
      - name: Extract short commit SHA
        id: short-sha
        run: echo "short_sha=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
      - name: Build APK with Gradle
        run: ./gradlew clean --refresh-dependencies assembleDebug
      - name: Check folder with APK
        run: ls -la ./app/build/outputs/apk/debug
      - name: upload-artifact
        id: upload-artifact
        uses: actions/upload-artifact@master
        with:
          name: cloudx-sdk-android-apk-${{ steps.extract-version.outputs.version }}
          path: ./app/build/outputs/apk/debug/cloudx-demo-debug-${{ steps.extract-version.outputs.version }}.apk

      - name: 📢 Slack Notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: custom
          custom_payload: |
            {
              "text": "🤖 CloudX Demo APK Build #${{ github.run_number }} finished",
              "attachments": [{
                "author_name": "cloudx-android/build-demo-android",
                "fallback": "Demo APK build pipeline finished",
                "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                "fields": [
                  {
                    "title": "Status",
                    "value": "${{ job.status == 'success' && '✅ Success' || '❌ Failed' }}",
                    "short": true
                  },
                  {
                    "title": "Version",
                    "value": "`${{ steps.extract-version.outputs.version }}`",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "`${{ github.ref_name }}`",
                    "short": true
                  },
                  {
                    "title": "Commit",
                    "value": "`${{ steps.short-sha.outputs.short_sha }}`",
                    "short": true
                  },
                  {
                    "title": "APK Status",
                    "value": "${{ job.status == 'success' && '📱 Demo APK built and uploaded' || '❌ APK build failed' }}",
                    "short": false
                  },
                  {
                    "title": "Pipeline Log",
                    "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Pipeline Log>",
                    "short": true
                  },
                  {
                    "title": "Artifacts",
                    "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Download APK>",
                    "short": true
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CLOUDX_ALERTS_MOBILE_SLACK }}

  dispatch:
    name: trigger-autotest
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'cloudx-io',
              repo: 'cloudexchange.sdk.automated.testing',
              workflow_id: 'android.yml',
              ref: 'master',
              inputs: {
                'artifact-url' : '${{ needs.build.outputs.artifact-url }}',
              },
            });