name: 🚀 Publish CloudX SDK

on:
  push:
    tags:
      - 'v-sdk-*'

env:
  ANDROID_HOME: /Users/administrator/Library/Android/sdk

jobs:
  determine-sdk:
    runs-on: self-hosted
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
      shouldPublish: ${{ steps.extract-version.outputs.shouldPublish }}
    steps:
      - name: 🏷 Extract version from tag
        id: extract-version
        run: |
          if [[ "${{ github.ref_name }}" == v-sdk-* ]]; then
            echo "version=${GITHUB_REF_NAME#v-sdk-}" >> $GITHUB_OUTPUT
            echo "shouldPublish=true" >> $GITHUB_OUTPUT
          else
            echo "No matching SDK tag pattern. Skipping..."
            echo "shouldPublish=false" >> $GITHUB_OUTPUT
            exit 0
          fi

  publish-sdk:
    needs: determine-sdk
    runs-on: self-hosted
    if: ${{ needs.determine-sdk.outputs.shouldPublish == 'true' }}
    name: 📦 Publish CloudX SDK
    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 🔐 Make Gradle executable
        run: chmod +x ./gradlew

      # Additional SDK checks can be added here
      - name: 🧪 Run SDK Tests
        run: ./gradlew :sdk:test

      - name: 📋 Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: sdk/build/test-results/**/*.xml

      - name: 📊 Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ github.run_number }}
          path: |
            sdk/build/reports/tests/
            sdk/build/test-results/

      - name: 🕵️ Log Maven Central and GPG Secrets (partially)
        run: |
          echo "🔐 mavenCentralUsername: ${ORG_GRADLE_PROJECT_mavenCentralUsername:0:4}"
          echo "🔐 mavenCentralPassword is set: [${#ORG_GRADLE_PROJECT_mavenCentralPassword}] characters"
          echo "🔏 signingInMemoryKey is set: $([ -z \"$ORG_GRADLE_PROJECT_signingInMemoryKey\" ] && echo '❌ NO' || echo '✅ YES')"
          echo "🔏 signingInMemoryKeyPassword is set: $([ -z \"$ORG_GRADLE_PROJECT_signingInMemoryKeyPassword\" ] && echo '❌ NO' || echo '✅ YES')"
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}

      - name: 🛠️ Build SDK Release AAR
        run: ./gradlew :sdk:assembleRelease -Pcloudx.endpoint.config=https://example.com/config.json -Pversion=${{ needs.determine-sdk.outputs.version }}

      - name: 📦 Publish SDK to Maven Central
        run: ./gradlew :sdk:publishToMavenCentral --no-daemon --stacktrace -Pcloudx.endpoint.config=https://example.com/config.json -Pversion=${{ needs.determine-sdk.outputs.version }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}

      - name: 📤 Upload SDK AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdk-release-${{ needs.determine-sdk.outputs.version }}
          path: sdk/build/outputs/aar/sdk-release.aar

      #      - name: 🚀 Create GitHub Release with SDK AAR
      #        uses: softprops/action-gh-release@v1
      #        with:
      #          name: Release ${{ github.ref_name }}
      #          tag_name: ${{ github.ref_name }}
      #          files: sdk/build/outputs/aar/sdk-release.aar
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📢 Slack Notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: custom
          custom_payload: |
            {
              "text": "🚀 CloudX SDK Publishing #${{ github.run_number }} finished",
              "attachments": [{
                "author_name": "cloudexchange.android.sdk/publish-sdk",
                "fallback": "SDK publishing pipeline finished",
                "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                "fields": [
                  {
                    "title": "Status",
                    "value": "${{ job.status == 'success' && '✅ Success' || '❌ Failed' }}",
                    "short": true
                  },
                  {
                    "title": "SDK Version",
                    "value": "`${{ needs.determine-sdk.outputs.version }}`",
                    "short": true
                  },
                  {
                    "title": "Tag",
                    "value": "`${{ github.ref_name }}`",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "`${{ github.ref_name }}`",
                    "short": true
                  },
                  {
                    "title": "Maven Central",
                    "value": "${{ job.status == 'success' && '📤 Uploaded to Maven Central (~30 min to publish)' || '❌ Upload failed' }}",
                    "short": false
                  },
                  {
                    "title": "Pipeline Log",
                    "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Pipeline Log>",
                    "short": true
                  },
                  {
                    "title": "Artifacts",
                    "value": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Download AAR>",
                    "short": true
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CLOUDX_ALERTS_MOBILE_SLACK }}