name: 🚀 Publish CloudX Module (Matrix)

on:
  push:
    tags:
      - 'v-*'

env:
  ANDROID_HOME: /Users/administrator/Library/Android/sdk
  PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  publish:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - module: adapter-cloudx
            path: adapter-cloudx
            tagPrefix: v-adapter-cloudx-
            artifactName: cloudx-adapter-cloudx-release.aar
          - module: adapter-meta
            path: adapter-meta
            tagPrefix: v-adapter-meta-
            artifactName: cloudx-adapter-meta-release.aar
          - module: adapter-google
            path: adapter-google
            tagPrefix: v-adapter-google-
            artifactName: cloudx-adapter-google-release.aar
          - module: adapter-mintegral
            path: adapter-mintegral
            tagPrefix: v-adapter-mintegral-
            artifactName: cloudx-adapter-mintegral-release.aar
          - module: adapter-testbidder
            path: adapter-testbidder
            tagPrefix: v-adapter-testbidder-
            artifactName: cloudx-adapter-testbidder-release.aar

    name: 📦 Publish ${{ matrix.module }}
    if: startsWith(github.ref, format('refs/tags/{0}', matrix.tagPrefix))
    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 🔐 Make Gradle executable
        run: chmod +x ./gradlew

      - name: 🛠 Build Release AAR
        run: ./gradlew :${{ matrix.path }}:assembleRelease -PuseRemoteSdk=true

      - name: 📦 Publish to Maven Central
        run: ./gradlew :${{ matrix.path }}:publishToMavenCentral --no-daemon --stacktrace -PuseRemoteSdk=true
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}

      - name: 📤 Upload AAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifactName }}
          path: ${{ matrix.path }}/build/outputs/aar/*.aar

      - name: 🚀 Create GitHub Release with AAR
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ${{ matrix.path }}/build/outputs/aar/*.aar
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
